name: Triggered Workflow

on:
  repository_dispatch:
    types: [custom_event_type]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello World!"

      - name: Print Event Parameters
        run: |
          echo "Param 1: ${{ github.event.client_payload.param1 }}"
          echo "Param 2: ${{ github.event.client_payload.param2 }}"
